version: '3.1'
services:
  db:
    image: mysql
    container_name: gympp
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - gymcontroll_data:/var/lib/mysql
volumes:
  gymcontroll_data:
